// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProximoTurnoApi.Infrastructure.Repositories;

#nullable disable

namespace ProximoTurnoApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JOGO_TAG", b =>
                {
                    b.Property<int>("ID_JOGO")
                        .HasColumnType("int");

                    b.Property<int>("ID_TAG")
                        .HasColumnType("int");

                    b.HasKey("ID_JOGO", "ID_TAG");

                    b.HasIndex("ID_TAG");

                    b.ToTable("JOGO_TAG");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProximoTurnoApi.Domain.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_HORA");

                    b.Property<DateTime?>("DataHoraEntrega")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_HORA_ENTREGA");

                    b.Property<int>("ID_CLIENTE")
                        .HasColumnType("int");

                    b.Property<int?>("ID_PEDIDO_ORIGINAL")
                        .HasColumnType("int");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_TOTAL");

                    b.HasKey("Id");

                    b.HasIndex("ID_CLIENTE");

                    b.HasIndex("ID_PEDIDO_ORIGINAL");

                    b.ToTable("PEDIDO", (string)null);
                });

            modelBuilder.Entity("ProximoTurnoApi.Infrastructure.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("CATEGORIA");
                });

            modelBuilder.Entity("ProximoTurnoApi.Infrastructure.Models.CategoriaPeriodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("ID_CATEGORIA")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeDias")
                        .HasColumnType("int")
                        .HasColumnName("QTDE_DIAS");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("ID_CATEGORIA");

                    b.ToTable("CATEGORIA_PERIODO", (string)null);
                });

            modelBuilder.Entity("ProximoTurnoApi.Infrastructure.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<bool>("AceitaReceberOfertas")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ACEITA_RECEBER_OFERTAS");

                    b.Property<string>("ComoNosConheceu")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("COMO_NOS_CONHECEU");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.ToTable("CLIENTE");
                });

            modelBuilder.Entity("ProximoTurnoApi.Infrastructure.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataDevolucao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_DEVOLUCAO");

                    b.Property<int>("IdJogoCopia")
                        .HasColumnType("int")
                        .HasColumnName("ID_JOGO_COPIA");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("ID_PEDIDO");

                    b.Property<bool>("Renovado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("RENOVADO");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("IdJogoCopia");

                    b.HasIndex("IdPedido");

                    b.ToTable("PEDIDO_ITEM");
                });

            modelBuilder.Entity("ProximoTurnoApi.Infrastructure.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("DataCompra")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_COMPRA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FOTO");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("ID_CATEGORIA");

                    b.Property<short>("IdadeMinima")
                        .HasColumnType("smallint")
                        .HasColumnName("IDADE_MINIMA");

                    b.Property<short>("MaximoDeJogadores")
                        .HasColumnType("smallint")
                        .HasColumnName("MAXIMO_JOGADORES");

                    b.Property<short>("MinimoDeJogadores")
                        .HasColumnType("smallint")
                        .HasColumnName("MINIMO_JOGADORES");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOME");

                    b.Property<TimeSpan?>("TempoEstimadoDeJogo")
                        .HasColumnType("time(6)")
                        .HasColumnName("TEMPO_ESTIMADO_JOGO");

                    b.Property<decimal?>("ValorDeCompra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_COMPRA");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.ToTable("JOGO");
                });

            modelBuilder.Entity("ProximoTurnoApi.Infrastructure.Models.JogoCopia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("IdJogo")
                        .HasColumnType("int")
                        .HasColumnName("ID_JOGO");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("IdJogo");

                    b.ToTable("JOGO_COPIA");
                });

            modelBuilder.Entity("ProximoTurnoApi.Infrastructure.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("IdJogo")
                        .HasColumnType("int")
                        .HasColumnName("ID_JOGO");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TITULO");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("URL");

                    b.HasKey("Id");

                    b.HasIndex("IdJogo");

                    b.ToTable("LINK");
                });

            modelBuilder.Entity("ProximoTurnoApi.Infrastructure.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("TAG");
                });

            modelBuilder.Entity("ProximoTurnoApi.Infrastructure.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("NOME");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("JOGO_TAG", b =>
                {
                    b.HasOne("ProximoTurnoApi.Infrastructure.Models.Jogo", null)
                        .WithMany()
                        .HasForeignKey("ID_JOGO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProximoTurnoApi.Infrastructure.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("ID_TAG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProximoTurnoApi.Infrastructure.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProximoTurnoApi.Infrastructure.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProximoTurnoApi.Infrastructure.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProximoTurnoApi.Infrastructure.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProximoTurnoApi.Domain.Pedido", b =>
                {
                    b.HasOne("ProximoTurnoApi.Infrastructure.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ID_CLIENTE")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProximoTurnoApi.Domain.Pedido", "PedidoOriginal")
                        .WithMany()
                        .HasForeignKey("ID_PEDIDO_ORIGINAL")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("PedidoOriginal");
                });

            modelBuilder.Entity("ProximoTurnoApi.Infrastructure.Models.CategoriaPeriodo", b =>
                {
                    b.HasOne("ProximoTurnoApi.Infrastructure.Models.Categoria", "Categoria")
                        .WithMany("Periodos")
                        .HasForeignKey("ID_CATEGORIA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ProximoTurnoApi.Infrastructure.Models.ItemPedido", b =>
                {
                    b.HasOne("ProximoTurnoApi.Infrastructure.Models.JogoCopia", "JogoCopia")
                        .WithMany()
                        .HasForeignKey("IdJogoCopia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProximoTurnoApi.Domain.Pedido", null)
                        .WithMany("Items")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JogoCopia");
                });

            modelBuilder.Entity("ProximoTurnoApi.Infrastructure.Models.Jogo", b =>
                {
                    b.HasOne("ProximoTurnoApi.Infrastructure.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ProximoTurnoApi.Infrastructure.Models.JogoCopia", b =>
                {
                    b.HasOne("ProximoTurnoApi.Infrastructure.Models.Jogo", "Jogo")
                        .WithMany("Copias")
                        .HasForeignKey("IdJogo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("ProximoTurnoApi.Infrastructure.Models.Link", b =>
                {
                    b.HasOne("ProximoTurnoApi.Infrastructure.Models.Jogo", null)
                        .WithMany("Links")
                        .HasForeignKey("IdJogo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProximoTurnoApi.Domain.Pedido", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProximoTurnoApi.Infrastructure.Models.Categoria", b =>
                {
                    b.Navigation("Periodos");
                });

            modelBuilder.Entity("ProximoTurnoApi.Infrastructure.Models.Jogo", b =>
                {
                    b.Navigation("Copias");

                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
